name: subscription_holder
description: Subscription Holder holds StreamSubscriptions and dispose all conveniently.
version: 2.1.0
homepage: https://github.com/mono0926/flutter_mono_kit
environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  rxdart: ">=0.26.0-0 <0.27.0"
  state_notifier: ">=0.7.0-0 <0.8.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
